#version: '3.8'

# 1. Define the custom network (Internal communication remains the same)
networks:
  capstone_net:
    driver: bridge

services:

  # 2a. The Frontend Container (Static HTML/CSS)
  web-frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: web_hippo_frontend
    # Map the internal Nginx port 80 to a unique public port (e.g., 2000) on the Ubuntu Server
    # NPM will proxy se1.centralspiral.pro to [Ubuntu Server IP]:2000
    ports:
      - "2000:80"
    restart: always
    networks:
      - capstone_net

  # 2b. The Backend Container (.NET API)
  web-backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: web_hippo_backend
    # Map the internal API port 8080 to a unique public port (e.g., 8081) on the Ubuntu Server
    # NPM will proxy se1.centralspiral.pro/api to [Ubuntu Server IP]:8081
    ports:
      - "8081:8080" 
    restart: always
    networks:
      - capstone_net
