# 1. Define the custom network (Internal communication remains the same)
networks:
  capstone_net:
    driver: bridge

services:

  # 2a. The Frontend Container (Static HTML/CSS)
  web-frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: web_hippo_frontend
    # Map the internal Nginx port 80 to a unique public port (e.g., 2000) on the Ubuntu Server
    # NPM will proxy se1.centralspiral.pro to [Ubuntu Server IP]:2000
    ports:
      - "2000:80"
    restart: always
    networks:
      - capstone_net

  # 2b. The Backend Container (.NET API)
  web-backend:
    image: capstone-web-backend
    environment:
      # This environment variable tells the Google client library where the key is located
      GOOGLE_APPLICATION_CREDENTIALS: /app/keyfile.json
    volumes:
      # Maps local key file into the container at the expected path
      - ./csc-4610-470418-85d894e69233.json:/app/keyfile.json
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: web_hippo_backend

    ports:
      - "0.0.0.0:8000:8000" 
    restart: always
    networks:
      - capstone_net
